"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import {
  Share2,
  ArrowRight,
  CheckCircle2,
  Sparkles,
  Search,
  Shield,
  Clock,
  ChevronRight,
  ChevronDown,
  BarChart3,
  Calendar,
  FileText,
  Video,
  Image,
  MessageCircle,
  Hash,
  TrendingUp,
  Users,
  Zap,
  Target,
  Check,
  X,
  Lightbulb,
  RefreshCw,
} from "lucide-react";

const stats = [
  { value: "4.9B", label: "Social media users worldwide — your audience is already on these platforms right now", icon: Users },
  { value: "54%", label: "Of consumers research brands on social before making a purchase decision", icon: Search },
  { value: "3×", label: "More leads generated by brands publishing consistently vs those posting sporadically", icon: TrendingUp },
  { value: "92%", label: "Of marketers say social media has generated more exposure for their business", icon: Share2 },
];

const painPoints = [
  {
    icon: Lightbulb,
    title: "Posting Randomly With No Strategy",
    description:
      "Throwing up content whenever someone has a spare 20 minutes is not a social media strategy. Without a content plan tied to your business goals, you're burning time for zero measurable return.",
    color: "text-red-500",
    bg: "bg-red-50",
  },
  {
    icon: Image,
    title: "Inconsistent Brand Voice & Visuals",
    description:
      "Different fonts, mismatched colours, varying tones across posts — your profile looks like three different businesses ran it. Inconsistency destroys trust before a potential customer ever visits your website.",
    color: "text-pink-500",
    bg: "bg-pink-50",
  },
  {
    icon: RefreshCw,
    title: "Running Out of Content Ideas Every Week",
    description:
      "The blank-page problem is real. Most businesses exhaust their content ideas within weeks and resort to reposting competitors or going silent for stretches. Neither builds an audience.",
    color: "text-rose-500",
    bg: "bg-rose-50",
  },
  {
    icon: MessageCircle,
    title: "Low Engagement Despite Regular Posting",
    description:
      "You post consistently but get three likes and a comment from your mum. Reach and engagement don't come from volume alone — they come from algorithm-native formats, optimal timing, and content that earns a reaction.",
    color: "text-violet-500",
    bg: "bg-violet-50",
  },
  {
    icon: Target,
    title: "On the Wrong Platforms for Your Audience",
    description:
      "Spending hours on Facebook when your buyers are on LinkedIn. Ignoring TikTok when your demographic spends 95 minutes a day there. Platform mismatch means maximum effort for minimum result.",
    color: "text-amber-500",
    bg: "bg-amber-50",
  },
  {
    icon: Clock,
    title: "No Time to Create, Schedule AND Engage",
    description:
      "Running a business and managing social media is a full-time job in itself. Something always slips — usually the engagement and replies that actually build a community and convert followers into buyers.",
    color: "text-slate-500",
    bg: "bg-slate-50",
  },
];

const deliverables = [
  {
    icon: Calendar,
    title: "Content Strategy & 30-Day Calendar",
    description:
      "A monthly content calendar built around your goals, audience, and platform algorithms — every post planned with a purpose, approved before it goes live, and spaced to maximise reach and consistency.",
    color: "text-pink-600",
    bg: "bg-pink-50",
  },
  {
    icon: Users,
    title: "LinkedIn Content & Thought Leadership",
    description:
      "Long-form posts, carousels, polls, and founder-voice content that positions you as an authority in your industry — built to generate inbound enquiries and grow your professional network.",
    color: "text-rose-600",
    bg: "bg-rose-50",
  },
  {
    icon: Video,
    title: "TikTok & Instagram Reels Production",
    description:
      "Short-form video scripts, hooks, captions, and editing guidelines — optimised for the TikTok and Reels algorithm, designed to reach cold audiences and grow your following organically.",
    color: "text-fuchsia-600",
    bg: "bg-fuchsia-50",
  },
  {
    icon: Share2,
    title: "YouTube Shorts & Long-Form Strategy",
    description:
      "YouTube Shorts for discoverability and long-form video strategy for authority — titles, descriptions, tags, and thumbnail direction all optimised for search and suggested placements.",
    color: "text-red-600",
    bg: "bg-red-50",
  },
  {
    icon: Image,
    title: "Branded Graphic Design & Templates",
    description:
      "Every static post, carousel, story, and cover image designed to your brand guidelines — consistent colours, typography, and visual language across every platform so your profile looks like a premium brand.",
    color: "text-violet-600",
    bg: "bg-violet-50",
  },
  {
    icon: MessageCircle,
    title: "Community Management & Engagement",
    description:
      "Daily monitoring of comments, DMs, and mentions — responded to on-brand and on-time. Building real community engagement is what converts followers into customers and customers into advocates.",
    color: "text-sky-600",
    bg: "bg-sky-50",
  },
  {
    icon: Hash,
    title: "Hashtag Research & Caption Optimisation",
    description:
      "Platform-specific hashtag strategy and SEO-optimised captions that expand organic reach, attract the right audience, and feed the algorithm signals that determine whether your content gets seen.",
    color: "text-indigo-600",
    bg: "bg-indigo-50",
  },
  {
    icon: BarChart3,
    title: "Monthly Analytics & Performance Report",
    description:
      "A clear monthly report covering reach, engagement rate, follower growth, top-performing content, and audience insights — with strategic recommendations to sharpen the next month's calendar.",
    color: "text-teal-600",
    bg: "bg-teal-50",
  },
];

const buildSteps = [
  {
    step: "01",
    title: "Brand Audit & Competitor Research",
    description:
      "We audit your existing profiles, benchmark your top competitors, identify your best-performing content to date, and map the platforms and content types that will generate the highest ROI for your specific audience.",
    icon: Search,
    color: "text-pink-600",
    bg: "bg-pink-50",
    border: "border-pink-100",
    duration: "Days 1–3",
  },
  {
    step: "02",
    title: "Strategy & Content Calendar Build",
    description:
      "We build your full content strategy — platform mix, post frequency, content pillars, content types, and a 30-day calendar that maps every post to a specific goal before a single piece is created.",
    icon: Calendar,
    color: "text-rose-600",
    bg: "bg-rose-50",
    border: "border-rose-100",
    duration: "Days 4–7",
  },
  {
    step: "03",
    title: "Creative Production & Approval",
    description:
      "We produce all graphics, write all captions, create all video scripts, and deliver the full month's content for your review and approval — nothing goes live without a sign-off from your team.",
    icon: Image,
    color: "text-[#046BAF]",
    bg: "bg-blue-50",
    border: "border-blue-100",
    duration: "Days 8–14",
  },
  {
    step: "04",
    title: "Publishing, Scheduling & Engagement",
    description:
      "Content is scheduled at platform-optimised times. We monitor comments and DMs daily, engage with your audience, and flag anything requiring your personal attention — community management runs 7 days a week.",
    icon: Share2,
    color: "text-fuchsia-600",
    bg: "bg-fuchsia-50",
    border: "border-fuchsia-100",
    duration: "Ongoing",
  },
  {
    step: "05",
    title: "Monthly Review & Strategy Refresh",
    description:
      "Every month we review the data — what's growing, what's converting, what the algorithm rewarded — and refresh the strategy accordingly. Content that works gets amplified. Content that doesn't gets replaced.",
    icon: BarChart3,
    color: "text-violet-600",
    bg: "bg-violet-50",
    border: "border-violet-100",
    duration: "Monthly",
  },
];

const comparisonFeatures = [
  "Platform-Native Content Creation",
  "Brand-Consistent Graphic Design",
  "Short-Form Video (TikTok / Reels)",
  "LinkedIn Thought Leadership",
  "YouTube Shorts Management",
  "Community Management & Replies",
  "Hashtag & Caption Strategy",
  "Monthly Performance Reporting",
  "Multi-Platform Strategy",
  "Dedicated Content Team",
];

const comparisonData = [
  {
    label: "Buffer / Later (DIY)",
    values: [false, false, false, false, false, false, "basic", "basic", false, false],
    highlight: false,
  },
  {
    label: "Hootsuite Agency",
    values: ["limited", "limited", false, false, false, "extra cost", true, true, "limited", false],
    highlight: false,
  },
  {
    label: "In-House Hire",
    values: [true, "limited", "limited", "limited", false, true, true, true, "limited", false],
    highlight: false,
  },
  {
    label: "Kazi Agency",
    values: [true, true, true, true, true, true, true, true, true, true],
    highlight: true,
  },
];

const faqs = [
  {
    q: "Which social media platforms do you manage?",
    a: "We manage LinkedIn, TikTok, Instagram (feed posts, Reels, Stories), YouTube (Shorts and long-form strategy), and Facebook. The platforms we prioritise for your business depend entirely on where your audience spends time and where you're most likely to generate leads or sales. During the strategy phase, we recommend a platform mix based on your industry, buyer persona, and goals — most clients focus on 2–3 platforms at full depth rather than spreading thin across all five.",
  },
  {
    q: "How many posts per week do we get?",
    a: "Post frequency varies by platform and package. As a general guide: LinkedIn (3–5 posts per week), Instagram (4–6 posts per week including Reels and Stories), TikTok (3–5 videos per week), YouTube Shorts (2–3 per week). We set the exact cadence during strategy based on what the algorithm rewards for your niche and what your audience engagement data supports — more is not always better, and we won't inflate post counts just to hit a number.",
  },
  {
    q: "Do you create all the content, or do we need to provide material?",
    a: "We produce everything: copy, graphics, captions, hashtags, and video scripts. For video content, we work from a brief or script and can direct the production if you're filming, or we can produce fully designed video content using your brand assets. If you want to contribute raw footage, behind-the-scenes content, or founder commentary, we can incorporate that into the content mix — many clients find this produces the highest-performing content. But there's no requirement. We can run your entire social presence without you writing a word.",
  },
  {
    q: "How do you handle comments and DMs?",
    a: "We monitor your profiles daily (7 days a week) and respond to comments and DMs on-brand and promptly. We build a custom response framework during onboarding — tone of voice guidelines, common Q&A responses, escalation rules for sales enquiries or complaints, and topics that require your personal response. Anything that falls outside our response remit (a specific sales enquiry, a complaint requiring account access, a media request) is flagged to you immediately with a suggested response for your review.",
  },
  {
    q: "Can you grow our follower count?",
    a: "Follower growth is a byproduct of the right content strategy — not something we game with follow-unfollow tactics or purchased followers, which damage your account's credibility and algorithm standing. We grow audiences through consistent platform-native content, strong engagement rates that signal quality to algorithms, strategic hashtag and SEO optimisation, and cross-promotion between platforms. Organic growth takes 3–6 months to build momentum, but the audience you earn this way actually converts. We track follower quality, not just quantity.",
  },
  {
    q: "Do you run paid social ads as well?",
    a: "Paid social advertising (Meta Ads, LinkedIn Ads, TikTok Ads) is a separate service — our Paid Advertising package. However, the two work extremely well together: organic content builds trust and warms the audience, while paid ads amplify your best-performing organic posts and target cold audiences at scale. Many clients run both simultaneously, and we coordinate creative assets and targeting across both to avoid message overlap and maximise efficiency.",
  },
  {
    q: "How long before we see meaningful results?",
    a: "The first month is primarily about getting the strategy, brand identity, and content production workflow right. Months 2–3 are where engagement starts to build as the algorithm learns your content and your audience grows. Meaningful lead generation from organic social typically emerges at 3–6 months for most businesses, with the accounts that stay consistent seeing compounding growth from month 4 onwards. We set realistic expectations at the start and report progress transparently every month — including what's working and what we're adjusting.",
  },
  {
    q: "What do you need from us to get started?",
    a: "To onboard effectively, we need: access to your social media accounts (we'll manage everything from there), your brand assets (logo, colour palette, font guidelines — if you don't have these, we can create a basic brand kit), a completed onboarding questionnaire about your business, target audience, and goals, and a kick-off call to walk through the strategy before we build anything. Most clients are fully onboarded and producing content within 5–7 business days of sign-up.",
  },
  {
    q: "Do you offer content approval before anything goes live?",
    a: "Yes — always. Every piece of content (graphics, captions, video scripts, stories) is delivered to you for review and approval before it's scheduled or published. We use a shared content calendar or approval tool depending on your preference, and we build enough lead time so you never feel rushed. Most clients review and approve a full month's content in one sitting within the first week of each month. You have final say on everything — nothing goes live without your sign-off.",
  },
];

const platformItems = [
  {
    id: "linkedin",
    name: "LinkedIn",
    tagline: "B2B & Thought Leadership",
    iconBg: "#EFF6FF",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#0A66C2] flex items-center justify-center text-white font-black text-[9px] shrink-0">
        in
      </span>
    ),
  },
  {
    id: "tiktok",
    name: "TikTok",
    tagline: "Short-Form Video & Reach",
    iconBg: "#FFF0F4",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#010101] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        TT
      </span>
    ),
  },
  {
    id: "instagram",
    name: "Instagram",
    tagline: "Reels, Stories & Feed",
    iconBg: "#FFF0F7",
    icon: (
      <span className="w-6 h-6 rounded-md bg-gradient-to-br from-[#833ab4] via-[#fd1d1d] to-[#fcb045] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        IG
      </span>
    ),
  },
  {
    id: "youtube",
    name: "YouTube",
    tagline: "Shorts & Long-Form",
    iconBg: "#FFF2F2",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#FF0000] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        YT
      </span>
    ),
  },
  {
    id: "facebook",
    name: "Facebook",
    tagline: "Community & Reach",
    iconBg: "#EFF6FF",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#1877F2] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        fb
      </span>
    ),
  },
  {
    id: "canva",
    name: "Canva Pro",
    tagline: "Brand-Consistent Design",
    iconBg: "#FFF0F7",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#7D2AE8] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        Cv
      </span>
    ),
  },
  {
    id: "capcut",
    name: "CapCut",
    tagline: "Video Editing",
    iconBg: "#F0FDF4",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#000000] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        CC
      </span>
    ),
  },
  {
    id: "buffer",
    name: "Buffer / Later",
    tagline: "Scheduling & Analytics",
    iconBg: "#FFF7ED",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#F97316] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        Bf
      </span>
    ),
  },
];

export default function SocialMediaManagementPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <main className="bg-white">

      {/* ── Hero ── */}
      <section className="relative overflow-hidden pt-32 pb-24 px-6 bg-gradient-to-br from-white via-pink-50/40 to-rose-50">
        <div aria-hidden className="absolute inset-0 -z-10 pointer-events-none">
          <div className="absolute left-[-8%] top-[-8%] w-[500px] h-[500px] rounded-full bg-gradient-to-tr from-pink-500/20 to-rose-400/10 blur-3xl" />
          <div className="absolute right-[-6%] bottom-[-6%] w-[420px] h-[420px] rounded-full bg-gradient-to-br from-rose-400/15 to-pink-500/10 blur-3xl" />
        </div>

        <div className="max-w-7xl mx-auto">
          {/* Breadcrumb */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex items-center gap-2 text-sm text-slate-500 mb-8 justify-center"
          >
            <Link href="/" className="hover:text-[#046BAF] transition-colors">Home</Link>
            <ChevronRight className="w-3 h-3" />
            <Link href="/services" className="hover:text-[#046BAF] transition-colors">Services</Link>
            <ChevronRight className="w-3 h-3" />
            <span className="text-pink-600 font-medium">Social Media Management</span>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="max-w-4xl mx-auto text-center"
          >
            <div className="inline-flex items-center gap-2 mb-5 px-4 py-2 rounded-full bg-pink-50 border border-pink-200">
              <Share2 className="w-4 h-4 text-pink-600" />
              <span className="text-xs font-bold text-pink-700 tracking-widest uppercase">
                Social Media Management
              </span>
            </div>

            <h1 className="text-4xl md:text-5xl font-semibold text-slate-900 mb-6 text-balance leading-tight">
              Stop Posting Into the Void — Start Building a{" "}
              <span className="bg-gradient-to-r from-pink-500 to-rose-500 bg-clip-text text-transparent">
                Social Presence That Generates Real Leads
              </span>
            </h1>

            <p className="text-xl text-slate-600 mb-10 max-w-3xl mx-auto leading-relaxed">
              Most businesses post inconsistently, run out of ideas, and get zero engagement — then wonder why social media isn&apos;t working. Kazi Agency creates, schedules, and manages your entire social presence across LinkedIn, TikTok, Instagram, and YouTube — with a strategy built to grow your audience and convert followers into customers.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/book-a-consultation"
                className="bg-pink-600 hover:bg-pink-700 text-white px-8 py-4 rounded-xl font-bold text-base transition-all inline-flex items-center gap-2 justify-center"
              >
                Get a Free Social Media Audit
                <ArrowRight className="w-4 h-4" />
              </Link>
              <button
                onClick={() => document.getElementById("how-it-works")?.scrollIntoView({ behavior: "smooth", block: "start" })}
                className="border-2 border-pink-600 text-pink-600 hover:bg-pink-600 hover:text-white px-8 py-4 rounded-xl font-bold text-base transition-all inline-flex items-center gap-2 justify-center cursor-pointer"
              >
                See How It Works
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </motion.div>

          {/* Stats bar */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-4"
          >
            {stats.map((stat) => {
              const Icon = stat.icon;
              return (
                <div
                  key={stat.label}
                  className="bg-white rounded-2xl border border-slate-200 px-6 py-5 text-center shadow-sm"
                >
                  <Icon className="w-5 h-5 text-pink-600 mx-auto mb-2" />
                  <p className="text-3xl font-bold text-slate-900">{stat.value}</p>
                  <p className="text-sm text-slate-500 mt-1 leading-snug">{stat.label}</p>
                </div>
              );
            })}
          </motion.div>
        </div>
      </section>

      {/* ── Pain Points ── */}
      <section className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-red-50 border border-red-100">
              <span className="text-xs font-bold text-red-600 tracking-widest uppercase">
                The Problem
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              Why Your Social Media Isn&apos;t Working — And How to Fix It
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              These six problems show up in almost every brand audit we run — and each one is silently killing your reach, engagement, and leads.
            </p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {painPoints.map((point, i) => {
              const Icon = point.icon;
              return (
                <motion.div
                  key={point.title}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.08 }}
                  className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-slate-300 hover:shadow-md transition-all"
                >
                  <div className={`${point.bg} w-11 h-11 rounded-xl flex items-center justify-center mb-4`}>
                    <Icon className={`w-5 h-5 ${point.color}`} />
                  </div>
                  <h3 className="font-bold text-slate-900 mb-2">{point.title}</h3>
                  <p className="text-sm text-slate-500 leading-relaxed">{point.description}</p>
                </motion.div>
              );
            })}
          </div>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-12 text-center"
          >
            <p className="text-lg text-slate-600 mb-6">
              Sound familiar? Here&apos;s exactly how we fix all of it.
            </p>
            <Link
              href="/book-a-consultation"
              className="inline-flex items-center gap-2 bg-pink-600 hover:bg-pink-700 text-white px-7 py-3.5 rounded-xl font-bold transition-all"
            >
              Fix My Social Media — Free Audit
              <ArrowRight className="w-4 h-4" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ── What's Included ── */}
      <section className="py-24 px-6 bg-pink-50/40">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-pink-100 border border-pink-200">
              <span className="text-xs font-bold text-pink-700 tracking-widest uppercase">
                What&apos;s Included
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              Eight Deliverables That Turn Your Social Into a Lead-Generation Machine
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              Every Kazi Agency social media engagement includes these eight core deliverables — fully created, scheduled, and optimised each month.
            </p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {deliverables.map((item, i) => {
              const Icon = item.icon;
              return (
                <motion.div
                  key={item.title}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.07 }}
                  className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-pink-200 hover:shadow-md transition-all"
                >
                  <div className={`${item.bg} w-11 h-11 rounded-xl flex items-center justify-center mb-4`}>
                    <Icon className={`w-5 h-5 ${item.color}`} />
                  </div>
                  <h3 className="font-bold text-slate-900 mb-2 text-sm leading-snug">{item.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed">{item.description}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Platforms We Manage (Infinity Slider) ── */}
      <section className="py-16 bg-white border-y border-slate-100">
        <div className="max-w-5xl mx-auto px-6 mb-10">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-pink-100 border border-pink-200">
              <span className="text-xs font-bold text-pink-700 tracking-widest uppercase">
                Platforms & Tools
              </span>
            </div>
            <h2 className="text-2xl md:text-3xl font-semibold text-slate-900 mb-3">
              Every Platform Your Audience Uses — Managed by Experts
            </h2>
            <p className="text-slate-500 max-w-2xl mx-auto text-base">
              We create platform-native content for each channel — not the same post copy-pasted everywhere — because each algorithm rewards a different format, length, and style.
            </p>
          </motion.div>
        </div>

        <div className="relative overflow-hidden">
          <div className="absolute left-0 top-0 bottom-0 w-24 z-10 bg-gradient-to-r from-white to-transparent pointer-events-none" />
          <div className="absolute right-0 top-0 bottom-0 w-24 z-10 bg-gradient-to-l from-white to-transparent pointer-events-none" />

          <div className="flex gap-4 animate-scroll-left w-max px-6">
            {[...platformItems, ...platformItems].map((platform, i) => (
              <div
                key={`${platform.id}-${i}`}
                className="flex items-center gap-3 bg-white border border-slate-200 rounded-2xl px-5 py-3.5 shadow-sm hover:shadow-md hover:border-pink-200 transition-all shrink-0 cursor-default"
              >
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                  style={{ backgroundColor: platform.iconBg }}
                >
                  {platform.icon}
                </div>
                <div>
                  <p className="font-bold text-slate-900 text-sm leading-none mb-1">{platform.name}</p>
                  <p className="text-xs text-slate-400 leading-none">{platform.tagline}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <p className="text-center text-sm text-slate-400 mt-8 px-6">
          Also supports Pinterest, X (Twitter), and Threads — platform selection is tailored to your specific audience and industry during onboarding.
        </p>
      </section>

      {/* ── Our Process ── */}
      <section id="how-it-works" className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-pink-100 border border-pink-200">
              <span className="text-xs font-bold text-pink-700 tracking-widest uppercase">
                How It Works
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              From Scattered Posts to a Consistent, Converting Social Presence
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              A proven five-phase process — strategy locked before a single post is created.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-5 gap-5 relative">
            <div
              aria-hidden
              className="hidden md:block absolute top-[52px] left-[calc(10%+24px)] right-[calc(10%+24px)] h-px bg-gradient-to-r from-transparent via-slate-200 to-transparent"
            />

            {buildSteps.map((step, i) => {
              const Icon = step.icon;
              return (
                <motion.div
                  key={step.step}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  className={`relative bg-white rounded-2xl border ${step.border} p-5 hover:shadow-lg transition-all`}
                >
                  <div className="flex items-center gap-3 mb-4">
                    <div className={`${step.bg} ${step.border} border w-12 h-12 rounded-xl flex items-center justify-center shrink-0`}>
                      <Icon className={`w-5 h-5 ${step.color}`} />
                    </div>
                    <span className="text-3xl font-black text-slate-100 select-none leading-none">
                      {step.step}
                    </span>
                  </div>
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">{step.duration}</p>
                  <h3 className="text-sm font-bold text-slate-900 mb-2">{step.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed">{step.description}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Comparison Table ── */}
      <section className="py-24 px-6 bg-pink-50/40">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-pink-100 border border-pink-200">
              <span className="text-xs font-bold text-pink-700 tracking-widest uppercase">
                Why Kazi Agency
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              Done-For-You Social vs. DIY Tools, Agencies & In-House
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              Scheduling tools don&apos;t create content. Here&apos;s how full-service social media management compares to every alternative.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="overflow-x-auto rounded-2xl border border-slate-200 shadow-sm bg-white"
          >
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-200">
                  <th className="text-left p-5 font-semibold text-slate-700 min-w-[200px]">Feature</th>
                  {comparisonData.map((col) => (
                    <th
                      key={col.label}
                      className={`p-5 text-center font-bold text-sm min-w-[150px] ${
                        col.highlight ? "text-pink-700 bg-pink-50/60" : "text-slate-500"
                      }`}
                    >
                      {col.label}
                      {col.highlight && (
                        <span className="block mt-1 text-[10px] bg-pink-600 text-white px-2 py-0.5 rounded-full font-bold mx-auto w-fit">
                          Best Value
                        </span>
                      )}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {comparisonFeatures.map((feature, fi) => (
                  <tr
                    key={feature}
                    className={`border-b border-slate-100 last:border-0 ${fi % 2 === 0 ? "bg-white" : "bg-slate-50/40"}`}
                  >
                    <td className="p-5 font-medium text-slate-700 text-sm">{feature}</td>
                    {comparisonData.map((col) => {
                      const val = col.values[fi];
                      return (
                        <td
                          key={col.label}
                          className={`p-5 text-center ${col.highlight ? "bg-pink-50/30" : ""}`}
                        >
                          {val === true ? (
                            <Check className="w-5 h-5 text-pink-600 mx-auto" />
                          ) : val === false ? (
                            <X className="w-4 h-4 text-red-400 mx-auto" />
                          ) : (
                            <span className="text-xs text-slate-400 font-medium">{val as string}</span>
                          )}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-10 bg-white rounded-2xl border border-pink-200 p-8"
          >
            <div className="grid md:grid-cols-3 gap-6 text-center">
              {[
                {
                  title: "Buffer / Later / Hootsuite",
                  cost: "$15–$249/mo",
                  note: "Great for scheduling — terrible for strategy. They move content around, but they don't create it, write it, design it, or tell you what to post. You still do all the work.",
                },
                {
                  title: "Typical Social Media Agency",
                  cost: "$1,500–$5,000/mo",
                  note: "Often specialises in one platform, outsources creative to junior staff, and locks you into a rigid content formula. Reporting is frequent but rarely tied to business outcomes.",
                },
                {
                  title: "Kazi Agency — Full Social Management",
                  cost: "Monthly retainer — fully done for you",
                  note: "Strategy, content creation, graphic design, video scripting, scheduling, community management, and monthly reporting — all executed by specialists across every platform you need.",
                  highlight: true,
                },
              ].map((item) => (
                <div
                  key={item.title}
                  className={`rounded-xl p-5 ${item.highlight ? "bg-pink-50 border border-pink-200" : "bg-slate-50"}`}
                >
                  <p className={`font-bold mb-1 ${item.highlight ? "text-pink-700" : "text-slate-700"}`}>
                    {item.title}
                  </p>
                  <p className={`text-xl font-black mb-2 ${item.highlight ? "text-pink-600" : "text-slate-900"}`}>
                    {item.cost}
                  </p>
                  <p className="text-xs text-slate-500 leading-relaxed">{item.note}</p>
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Why Kazi Agency ── */}
      <section className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <motion.div
              initial={{ opacity: 0, x: -24 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-pink-100 border border-pink-200">
                <span className="text-xs font-bold text-pink-700 tracking-widest uppercase">
                  Why Choose Us
                </span>
              </div>
              <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-6 text-balance">
                We Handle Your Entire Social Presence — You Just Show Up and Close the Leads
              </h2>
              <p className="text-lg text-slate-600 leading-relaxed mb-8">
                Most social media agencies pick one thing they&apos;re good at — usually graphics or copy — and do that on repeat. We build a complete content engine: strategy, platform-native creative, community management, and monthly analytics, all coordinated so your brand shows up consistently and compellingly wherever your buyers spend their time.
              </p>

              <div className="flex flex-col gap-4">
                {[
                  "Platform-native content — different format and voice for each channel",
                  "Content approval before anything goes live — you have final say, always",
                  "Video scripting and creative direction for TikTok, Reels, and Shorts",
                  "LinkedIn thought leadership that positions you as the go-to expert",
                  "Daily community management — comments and DMs handled 7 days a week",
                  "CRM-connected so social leads flow directly into your pipeline",
                ].map((point) => (
                  <div key={point} className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-pink-600 flex-shrink-0 mt-0.5" />
                    <span className="text-slate-700 font-medium">{point}</span>
                  </div>
                ))}
              </div>

              <div className="mt-10">
                <Link
                  href="/book-a-consultation"
                  className="inline-flex items-center gap-2 bg-pink-600 hover:bg-pink-700 text-white px-7 py-3.5 rounded-xl font-bold transition-all"
                >
                  Book a Free Social Strategy Call
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 24 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="grid grid-cols-1 sm:grid-cols-2 gap-5"
            >
              {[
                {
                  icon: Zap,
                  title: "Consistent Without the Burnout",
                  description:
                    "Consistency is the single most important factor in social media growth — and the hardest to maintain in-house. We remove the bottleneck so your brand shows up every week without you lifting a finger.",
                },
                {
                  icon: Video,
                  title: "Platform-Native Video First",
                  description:
                    "Short-form video is the highest-reach format on every major platform right now. We script, direct, and optimise Reels, TikToks, and Shorts so you capture the algorithm's attention before your competitors do.",
                },
                {
                  icon: Shield,
                  title: "Brand-Safe Everything",
                  description:
                    "Every post, reply, and graphic is reviewed against your brand guidelines before going live. Your brand voice is consistent — whether it's a LinkedIn article or a TikTok comment reply.",
                },
                {
                  icon: TrendingUp,
                  title: "Tied to Business Outcomes",
                  description:
                    "Follower counts are vanity. We measure reach, engagement rate, profile visits, link clicks, and — through CRM integration — actual leads and bookings generated from social. Every month.",
                },
              ].map((point, i) => {
                const Icon = point.icon;
                return (
                  <motion.div
                    key={point.title}
                    initial={{ opacity: 0, y: 16 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                    className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-pink-200 hover:shadow-md transition-all"
                  >
                    <div className="bg-pink-50 w-11 h-11 rounded-xl flex items-center justify-center mb-4">
                      <Icon className="w-5 h-5 text-pink-600" />
                    </div>
                    <h3 className="font-bold text-slate-900 mb-2">{point.title}</h3>
                    <p className="text-sm text-slate-500 leading-relaxed">
                      {point.description}
                    </p>
                  </motion.div>
                );
              })}
            </motion.div>
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="py-24 px-6 bg-pink-50/40">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-pink-100 border border-pink-200">
              <span className="text-xs font-bold text-pink-700 tracking-widest uppercase">
                FAQ
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              Common Questions About Social Media Management
            </h2>
            <p className="text-xl text-slate-600 max-w-2xl mx-auto">
              Everything you need to know before handing over your social presence.
            </p>
          </motion.div>

          <div className="flex flex-col gap-3">
            {faqs.map((faq, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
                className="bg-white rounded-2xl border border-slate-200 overflow-hidden"
              >
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between gap-4 p-6 text-left hover:bg-slate-50/50 transition-colors cursor-pointer"
                >
                  <span className="font-semibold text-slate-900 text-sm sm:text-base leading-snug">
                    {faq.q}
                  </span>
                  <ChevronDown
                    className={`w-5 h-5 text-pink-600 shrink-0 transition-transform duration-200 ${
                      openFaq === i ? "rotate-180" : ""
                    }`}
                  />
                </button>
                <AnimatePresence>
                  {openFaq === i && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.22 }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 pb-6 text-sm text-slate-600 leading-relaxed border-t border-slate-100 pt-4">
                        {faq.a}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="py-24 px-6 bg-gradient-to-br from-pink-600 to-rose-600 relative overflow-hidden">
        <div aria-hidden className="absolute inset-0 pointer-events-none">
          <div className="absolute left-[-10%] top-[-20%] w-[500px] h-[500px] rounded-full bg-white/5 blur-3xl" />
          <div className="absolute right-[-8%] bottom-[-15%] w-[400px] h-[400px] rounded-full bg-rose-300/10 blur-3xl" />
        </div>

        <div className="max-w-4xl mx-auto text-center relative">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <div className="inline-flex items-center gap-2 mb-5 px-4 py-2 rounded-full bg-white/15 border border-white/20">
              <Sparkles className="w-4 h-4 text-white" />
              <span className="text-xs font-bold text-white tracking-widest uppercase">
                Ready to Grow on Social?
              </span>
            </div>

            <h2 className="text-3xl md:text-4xl font-semibold text-white mb-6 text-balance">
              Let&apos;s Build a Social Media Presence That Actually Generates Business
            </h2>
            <p className="text-xl text-pink-100 mb-10 max-w-2xl mx-auto leading-relaxed">
              Book a free 30-minute social media audit. We&apos;ll review your current profiles, identify the biggest opportunities for growth, and show you exactly what a 90-day content roadmap looks like for your business.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/book-a-consultation"
                className="bg-white text-pink-600 hover:bg-pink-50 px-8 py-4 rounded-xl font-bold text-base transition-all inline-flex items-center gap-2 justify-center shadow-lg"
              >
                Book My Free Social Audit
                <ArrowRight className="w-4 h-4" />
              </Link>
              <Link
                href="/services"
                className="bg-white/10 hover:bg-white/20 border border-white/30 text-white px-8 py-4 rounded-xl font-bold text-base transition-all inline-flex items-center gap-2 justify-center"
              >
                Explore All Services
              </Link>
            </div>

            <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-6 text-pink-100 text-sm">
              {["No commitment required", "Free 30-minute strategy call", "Full 90-day content roadmap included"].map((item) => (
                <div key={item} className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-rose-200" />
                  {item}
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>
    </main>
  );
}
