"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import {
  Filter,
  ArrowRight,
  CheckCircle2,
  Sparkles,
  ChevronRight,
  ChevronDown,
  BarChart3,
  TrendingUp,
  Zap,
  Target,
  Check,
  X,
  MessageSquare,
  Users,
  Settings,
  FileText,
  Globe,
  Clock,
  Shield,
  DollarSign,
  Layers,
  Bell,
  MousePointer,
  Mail,
  PhoneCall,
  Star,
} from "lucide-react";

const stats = [
  { value: "79%", label: "Of marketing leads never convert into sales due to poor follow-up and lack of nurturing after initial capture", icon: Filter },
  { value: "5 min", label: "Response time is the threshold — leads contacted within 5 minutes are 21× more likely to qualify than those reached after 30", icon: Clock },
  { value: "451%", label: "More qualified leads generated by businesses using automated lead nurturing vs. those relying on manual follow-up alone", icon: TrendingUp },
  { value: "68%", label: "Of B2B businesses cite lead generation as their top marketing challenge — and most are solving it with the wrong tools", icon: Target },
];

const painPoints = [
  {
    icon: MousePointer,
    title: "Website Traffic With Zero Conversions",
    description:
      "You're spending on SEO and ads to drive visitors to your website — but most leave without doing anything. Without dedicated capture mechanisms (chat, forms, lead magnets, exit intent), 97% of your traffic disappears forever. Every unqualified visit is money left on the table.",
    color: "text-red-500",
    bg: "bg-red-50",
  },
  {
    icon: Filter,
    title: "No System to Qualify Leads Before They Reach Sales",
    description:
      "Your sales team wastes hours on discovery calls with leads who are the wrong size, the wrong budget, or the wrong stage of readiness. Without an upfront qualification layer — scoring questions, chatbot screening, or intake forms — every lead gets treated the same regardless of quality.",
    color: "text-orange-500",
    bg: "bg-orange-50",
  },
  {
    icon: Clock,
    title: "Slow Response Times Killing Hot Leads",
    description:
      "Research is unambiguous: leads contacted within 5 minutes of enquiring are 21× more likely to convert than those reached after 30 minutes. If your follow-up relies on someone manually checking an inbox, you're losing your hottest leads to competitors who respond instantly.",
    color: "text-amber-500",
    bg: "bg-amber-50",
  },
  {
    icon: Layers,
    title: "Leads Scattered Across Forms, Emails & Spreadsheets",
    description:
      "A contact form here, a Facebook Lead Ad there, a phone enquiry logged in a spreadsheet — leads fall through the gaps constantly. Without a centralised capture and routing system, you have no pipeline visibility, no follow-up consistency, and no way to measure what's actually working.",
    color: "text-violet-500",
    bg: "bg-violet-50",
  },
  {
    icon: BarChart3,
    title: "No Idea Which Channels Actually Generate Revenue",
    description:
      "You know how many leads came in this month. You have no idea whether they came from Google, your chatbot, a blog post, or a referral — or which of those sources produced leads that actually closed. Without source attribution, every channel decision is a guess.",
    color: "text-sky-500",
    bg: "bg-sky-50",
  },
  {
    icon: Mail,
    title: "No Lead Nurturing Between Capture and Close",
    description:
      "Most buyers aren't ready to purchase the moment they first engage. Without automated email and SMS nurturing sequences, cold leads go cold permanently. Competitors who nurture consistently win the client three months later when the buyer is finally ready — even though you were first.",
    color: "text-slate-500",
    bg: "bg-slate-50",
  },
];

const deliverables = [
  {
    icon: Globe,
    title: "Lead Capture Funnel Design & Build",
    description:
      "We design and build dedicated lead capture funnels — landing pages, multi-step forms, and conversion pathways — engineered to convert visitors into enquiries. Each funnel is built with a single goal, a clear value exchange, and friction-reduced UX to maximise capture rates from every traffic source.",
    color: "text-[#046BAF]",
    bg: "bg-sky-50",
  },
  {
    icon: MessageSquare,
    title: "AI Chatbot Setup & Deployment",
    description:
      "We build and deploy an AI-powered chatbot on your website that qualifies visitors 24/7 — asking the right questions, routing high-intent leads to booking, answering common objections, and capturing contact details even when your team is offline. Custom-trained on your business, products, and FAQs.",
    color: "text-cyan-600",
    bg: "bg-cyan-50",
  },
  {
    icon: FileText,
    title: "Smart Form & Quiz Funnel Implementation",
    description:
      "Multi-step forms and interactive quiz funnels that progressively collect lead data while simultaneously qualifying intent and segment. Built with conditional logic — so a £500/month prospect and a £50,000/month prospect get completely different experiences and routing from the first question.",
    color: "text-teal-600",
    bg: "bg-teal-50",
  },
  {
    icon: Star,
    title: "Lead Magnet Strategy & Creation",
    description:
      "High-value lead magnets — audits, calculators, guides, templates, and video trainings — that give prospects a compelling reason to exchange their contact details. We identify the format most suited to your buyer's decision stage and produce the asset, the landing page, and the delivery sequence.",
    color: "text-indigo-600",
    bg: "bg-indigo-50",
  },
  {
    icon: Target,
    title: "Lead Scoring & Qualification Framework",
    description:
      "Not all leads are equal. We build a lead scoring model inside your CRM that assigns points based on behaviour (pages visited, form fields completed, time on site), demographics (company size, industry, role), and engagement (email opens, chatbot interactions) — surfacing your hottest prospects automatically.",
    color: "text-violet-600",
    bg: "bg-violet-50",
  },
  {
    icon: Settings,
    title: "CRM Pipeline Integration & Routing",
    description:
      "Every lead captured — from any channel — is routed directly into your GoHighLevel CRM pipeline with full source attribution, tagged by campaign, segment, and qualification score. No manual data entry. No leads lost to inbox chaos. Instant notifications to the right team member the moment a hot lead arrives.",
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    icon: Zap,
    title: "Automated Follow-Up Sequences",
    description:
      "Instant, personalised follow-up the moment a lead converts — triggered SMS, email sequences, and task assignments that nurture prospects through the funnel without manual effort. Timing, messaging, and channel vary by lead score and segment so every prospect gets the right message at the right moment.",
    color: "text-orange-600",
    bg: "bg-orange-50",
  },
  {
    icon: BarChart3,
    title: "Lead Source Tracking & Monthly Reporting",
    description:
      "A clear monthly report breaking down leads by source (organic, paid, chatbot, referral, direct), by quality score, by stage reached, and by conversion to client. You see your true cost-per-lead and cost-per-acquisition by channel — so every future budget decision is driven by data, not instinct.",
    color: "text-rose-600",
    bg: "bg-rose-50",
  },
];

const buildSteps = [
  {
    step: "01",
    title: "Lead Audit & Strategy",
    description:
      "We audit your current lead flow — where traffic enters, where it drops off, how long follow-up takes, and which channels produce qualified vs. unqualified leads. We map your ideal buyer journey and design a capture system built around how your best clients actually make decisions.",
    icon: Filter,
    color: "text-[#046BAF]",
    bg: "bg-sky-50",
    border: "border-sky-100",
    duration: "Days 1–5",
  },
  {
    step: "02",
    title: "Funnel & Tech Build",
    description:
      "We build the capture infrastructure: landing pages, chatbot, smart forms, lead magnets, and CRM pipeline setup. Conversion tracking is configured before anything goes live — so every lead is attributed to the exact source and campaign that generated it.",
    icon: Settings,
    color: "text-cyan-600",
    bg: "bg-cyan-50",
    border: "border-cyan-100",
    duration: "Days 6–14",
  },
  {
    step: "03",
    title: "Launch & Automate",
    description:
      "Systems go live across your website, landing pages, and ad channels. Automated follow-up sequences fire the moment leads convert. CRM routing delivers each lead to the right team member instantly with full context — no manual processing required.",
    icon: Zap,
    color: "text-teal-600",
    bg: "bg-teal-50",
    border: "border-teal-100",
    duration: "Week 3",
  },
  {
    step: "04",
    title: "Optimise & Score",
    description:
      "Using real conversion data, we refine capture rates, adjust scoring thresholds, A/B test form copy and chatbot flows, and improve landing page performance. Lead quality is continuously measured — we improve the filter, not just the volume.",
    icon: Target,
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    border: "border-indigo-100",
    duration: "Month 2+",
  },
  {
    step: "05",
    title: "Report & Scale",
    description:
      "Monthly reporting shows exactly where your leads come from, what they cost, and how many converted. We identify your highest-performing acquisition channels and scale them — turning your lead generation system into a compounding, predictable pipeline.",
    icon: BarChart3,
    color: "text-violet-600",
    bg: "bg-violet-50",
    border: "border-violet-100",
    duration: "Ongoing",
  },
];

const comparisonFeatures = [
  "Lead Capture Funnel Build",
  "AI Chatbot (24/7 Qualification)",
  "Smart Form & Quiz Funnels",
  "Lead Magnet Creation",
  "Lead Scoring & Segmentation",
  "CRM Pipeline Integration",
  "Instant Automated Follow-Up",
  "Multi-Channel Lead Routing",
  "Monthly Lead Source Reporting",
  "Dedicated Lead Gen Strategist",
];

const comparisonData = [
  {
    label: "Contact Form (DIY)",
    values: [false, false, false, false, false, false, false, false, false, false],
    highlight: false,
  },
  {
    label: "Standalone Tools (e.g. Typeform)",
    values: ["limited", false, true, false, false, "manual", false, false, "basic", false],
    highlight: false,
  },
  {
    label: "Typical Lead Gen Agency",
    values: [true, "limited", "limited", "extra cost", false, "limited", "limited", false, true, false],
    highlight: false,
  },
  {
    label: "Kazi Agency",
    values: [true, true, true, true, true, true, true, true, true, true],
    highlight: true,
  },
];

const faqs = [
  {
    q: "What exactly is lead generation, and why does it need a system?",
    a: "Lead generation is the process of attracting strangers and converting them into people who have expressed interest in your business — by capturing their contact details, qualifying their intent, and moving them towards a sales conversation. Most businesses treat lead generation as a collection of disconnected tactics: a contact form here, a Facebook ad there. A lead generation system ties every capture point together — chatbots, forms, landing pages, lead magnets, and automated follow-up — into one integrated pipeline where every lead is captured, scored, routed, and nurtured automatically. The difference between a tactic and a system is that a system works whether or not anyone on your team is paying attention.",
  },
  {
    q: "How quickly will leads start coming in after you set things up?",
    a: "The capture infrastructure — chatbot, forms, landing pages, and CRM integration — is typically live within two to three weeks. If you're driving paid traffic, leads can start flowing within the first week of launch. If your lead generation is primarily organic (SEO, social media, referrals), volume depends on existing traffic levels, but the conversion rate on that traffic improves immediately once better capture mechanisms are in place. We also implement automated follow-up sequences from day one — so the leads you were already getting but losing due to slow response time start converting at a higher rate before any new traffic arrives.",
  },
  {
    q: "What's the difference between a lead and a qualified lead?",
    a: "A lead is anyone who has provided their contact details — name, email, phone number. A qualified lead is a lead who meets your target criteria: right company size, right budget, right decision-making authority, right timeline to buy. Capturing unqualified leads creates a sales problem — your team wastes time on prospects who were never going to buy. Our lead scoring and qualification framework filters leads at the point of capture through smart form logic and chatbot qualification questions, and then scores them inside the CRM based on behavioural signals. Hot, qualified leads are immediately flagged and routed to sales. Cold leads enter a nurture sequence. Your sales team only speaks to prospects worth their time.",
  },
  {
    q: "How does the AI chatbot work, and will it actually qualify leads properly?",
    a: "Our AI chatbots are built on GoHighLevel and trained specifically on your business — your services, pricing structure, ideal client profile, common objections, and FAQs. The chatbot engages website visitors in natural conversation, asks qualification questions (budget range, company size, timeline, specific need), and routes the conversation based on answers: high-intent leads are immediately pushed to book a call; mid-intent leads are captured and entered into a nurture sequence; low-intent leads receive educational content. The chatbot handles objections, provides social proof, and captures contact details — all without human involvement. Most clients see a 40–60% increase in lead capture from existing traffic within the first month of chatbot deployment.",
  },
  {
    q: "What is a lead magnet, and do I need one?",
    a: "A lead magnet is a free, high-value resource — a guide, calculator, template, audit, or mini-course — that gives a prospective buyer a compelling reason to exchange their contact details. They work because they offer immediate value before any commitment, and because the type of resource someone downloads tells you exactly where they are in the buying process. A business owner who downloads 'How to Calculate Your Marketing ROI' is further along in their decision journey than someone who requests 'The Beginner's Guide to Digital Marketing.' We identify the lead magnet format most aligned with how your buyers make decisions, produce the asset, build the landing page, and set up the automated delivery sequence. Lead magnets typically improve capture rates by 200–400% versus a generic 'contact us' form.",
  },
  {
    q: "How do leads from different channels (ads, organic, referral) all end up in one place?",
    a: "Every capture point — whether a form on your website, a chatbot conversation, a Facebook Lead Ad, a LinkedIn Lead Gen Form, or a landing page from a Google Ads campaign — is integrated with your GoHighLevel CRM via webhook, Zapier, or native integration. Each lead is tagged with its source, campaign, and entry point automatically. When a lead arrives in the CRM, it carries the full context: where they came from, what they downloaded or engaged with, what questions they answered, and what their lead score is. Your team sees all leads in one pipeline regardless of channel, and your monthly reporting breaks down volume, quality, and conversion rate by source so you know exactly where to invest next.",
  },
  {
    q: "Do you handle the automated follow-up sequences, or is that a separate service?",
    a: "Automated follow-up sequences are included as part of every lead generation engagement. The moment a lead is captured, a sequence fires immediately: a personalised email confirming receipt, an SMS with a direct next step (book a call, access a resource, answer a question), and a series of nurture emails over the following days and weeks designed to move the lead towards a sales conversation. Sequences are segmented by lead source, qualification score, and service interest — so a cold lead who downloaded a guide gets different messaging than a hot lead who answered three qualification questions and viewed your pricing page. We write the copy, build the automations, and set up the delivery logic. You approve everything before it goes live.",
  },
  {
    q: "What industries do your lead generation systems work for?",
    a: "Our lead generation systems work for any service business where leads are the primary input to a sales process — professional services (law, accounting, consulting), home services (construction, landscaping, HVAC, cleaning), healthcare and wellness, B2B SaaS, financial services, real estate, recruitment, and digital agencies. The fundamentals — capture, qualify, route, nurture — are the same across every industry. What changes is the qualification criteria, the lead magnet format, the chatbot scripts, and the nurture sequence messaging. In your strategy session, we research your specific buyer's decision journey and build the system around how they actually evaluate and select a provider in your category.",
  },
  {
    q: "How do you measure whether the lead generation system is actually working?",
    a: "We track and report on six core metrics every month: total leads captured (by channel and source), lead-to-qualified-lead rate (what percentage meet your target criteria), cost-per-lead (by channel), cost-per-qualified-lead, time-to-first-contact (how quickly leads receive follow-up), and lead-to-client conversion rate. These metrics give you a complete picture — not just how many leads came in, but how good they were and what happened to them afterwards. Most lead generation reporting stops at volume. We track the full journey from capture to closed client so you always know the real revenue impact of every channel and every campaign.",
  },
];

const toolItems = [
  {
    id: "ghl",
    name: "GoHighLevel CRM",
    tagline: "Lead Pipeline & Automation",
    iconBg: "#F0FDF4",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#16A34A] flex items-center justify-center text-white font-black text-[9px] shrink-0">
        GH
      </span>
    ),
  },
  {
    id: "chatbot",
    name: "AI Chatbot Builder",
    tagline: "24/7 Lead Qualification",
    iconBg: "#EFF6FF",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#046BAF] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        AI
      </span>
    ),
  },
  {
    id: "typeform",
    name: "Typeform / JotForm",
    tagline: "Smart Forms & Quizzes",
    iconBg: "#F0F9FF",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#0EA5E9] flex items-center justify-center text-white font-black text-[9px] shrink-0">
        Tf
      </span>
    ),
  },
  {
    id: "zapier",
    name: "Zapier",
    tagline: "Cross-Channel Routing",
    iconBg: "#FFF7ED",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#FF4A00] flex items-center justify-center text-white font-black text-[9px] shrink-0">
        Zp
      </span>
    ),
  },
  {
    id: "meta-leads",
    name: "Meta Lead Ads",
    tagline: "Facebook & Instagram Capture",
    iconBg: "#EFF6FF",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#0866FF] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        Mb
      </span>
    ),
  },
  {
    id: "linkedin-lgf",
    name: "LinkedIn Lead Gen Forms",
    tagline: "B2B In-Platform Capture",
    iconBg: "#EFF6FF",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#0A66C2] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        Li
      </span>
    ),
  },
  {
    id: "ga4",
    name: "Google Analytics 4",
    tagline: "Source Attribution",
    iconBg: "#FFF3E0",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#E37400] flex items-center justify-center text-white font-black text-[8px] shrink-0">
        GA4
      </span>
    ),
  },
  {
    id: "calendly",
    name: "Calendly / Cal.com",
    tagline: "Direct Booking Integration",
    iconBg: "#F0FDF4",
    icon: (
      <span className="w-6 h-6 rounded-md bg-[#006BFF] flex items-center justify-center text-white font-black text-[9px] shrink-0">
        Ca
      </span>
    ),
  },
];

export default function LeadGenerationPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <main className="bg-white">

      {/* ── Hero ── */}
      <section className="relative overflow-hidden pt-32 pb-24 px-6 bg-gradient-to-br from-white via-sky-50/40 to-cyan-50">
        <div aria-hidden className="absolute inset-0 -z-10 pointer-events-none">
          <div className="absolute left-[-8%] top-[-8%] w-[500px] h-[500px] rounded-full bg-gradient-to-tr from-[#046BAF]/20 to-cyan-400/10 blur-3xl" />
          <div className="absolute right-[-6%] bottom-[-6%] w-[420px] h-[420px] rounded-full bg-gradient-to-br from-cyan-400/15 to-[#046BAF]/10 blur-3xl" />
        </div>

        <div className="max-w-7xl mx-auto">
          {/* Breadcrumb */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex items-center gap-2 text-sm text-slate-500 mb-8 justify-center"
          >
            <Link href="/" className="hover:text-[#046BAF] transition-colors">Home</Link>
            <ChevronRight className="w-3 h-3" />
            <Link href="/services" className="hover:text-[#046BAF] transition-colors">Services</Link>
            <ChevronRight className="w-3 h-3" />
            <span className="text-[#046BAF] font-medium">Lead Generation</span>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="max-w-4xl mx-auto text-center"
          >
            <div className="inline-flex items-center gap-2 mb-5 px-4 py-2 rounded-full bg-sky-50 border border-sky-200">
              <Filter className="w-4 h-4 text-[#046BAF]" />
              <span className="text-xs font-bold text-[#046BAF] tracking-widest uppercase">
                Lead Generation
              </span>
            </div>

            <h1 className="text-4xl md:text-5xl font-semibold text-slate-900 mb-6 text-balance leading-tight">
              Stop Losing Visitors. Start Capturing{" "}
              <span className="bg-gradient-to-r from-[#046BAF] to-cyan-500 bg-clip-text text-transparent">
                Qualified Leads Into Your Pipeline — 24/7
              </span>
            </h1>

            <p className="text-xl text-slate-600 mb-10 max-w-3xl mx-auto leading-relaxed">
              Kazi Agency builds complete lead generation systems — AI chatbots, smart capture funnels, lead scoring, automated follow-up, and CRM integration — so every visitor has a clear path to becoming a lead, every lead is qualified before it reaches your sales team, and no enquiry falls through the cracks again.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/book-a-consultation"
                className="bg-[#046BAF] hover:bg-[#035a94] text-white px-8 py-4 rounded-xl font-bold text-base transition-all inline-flex items-center gap-2 justify-center"
              >
                Get a Free Lead Audit
                <ArrowRight className="w-4 h-4" />
              </Link>
              <button
                onClick={() => document.getElementById("how-it-works")?.scrollIntoView({ behavior: "smooth", block: "start" })}
                className="border-2 border-[#046BAF] text-[#046BAF] hover:bg-[#046BAF] hover:text-white px-8 py-4 rounded-xl font-bold text-base transition-all inline-flex items-center gap-2 justify-center cursor-pointer"
              >
                See How It Works
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </motion.div>

          {/* Stats bar */}
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-4"
          >
            {stats.map((stat) => {
              const Icon = stat.icon;
              return (
                <div
                  key={stat.label}
                  className="bg-white rounded-2xl border border-slate-200 px-6 py-5 text-center shadow-sm"
                >
                  <Icon className="w-5 h-5 text-[#046BAF] mx-auto mb-2" />
                  <p className="text-3xl font-bold text-slate-900">{stat.value}</p>
                  <p className="text-sm text-slate-500 mt-1 leading-snug">{stat.label}</p>
                </div>
              );
            })}
          </motion.div>
        </div>
      </section>

      {/* ── Pain Points ── */}
      <section className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-red-50 border border-red-100">
              <span className="text-xs font-bold text-red-600 tracking-widest uppercase">
                The Problem
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              Why Most Businesses Haemorrhage Leads Every Single Day
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              These six problems appear in almost every business we audit — and each one is silently draining the return on every pound you spend driving traffic.
            </p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {painPoints.map((point, i) => {
              const Icon = point.icon;
              return (
                <motion.div
                  key={point.title}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.08 }}
                  className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-slate-300 hover:shadow-md transition-all"
                >
                  <div className={`${point.bg} w-11 h-11 rounded-xl flex items-center justify-center mb-4`}>
                    <Icon className={`w-5 h-5 ${point.color}`} />
                  </div>
                  <h3 className="font-bold text-slate-900 mb-2">{point.title}</h3>
                  <p className="text-sm text-slate-500 leading-relaxed">{point.description}</p>
                </motion.div>
              );
            })}
          </div>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-12 text-center"
          >
            <p className="text-lg text-slate-600 mb-6">
              Sound familiar? Here&apos;s exactly how we fix every one of these.
            </p>
            <Link
              href="/book-a-consultation"
              className="inline-flex items-center gap-2 bg-[#046BAF] hover:bg-[#035a94] text-white px-7 py-3.5 rounded-xl font-bold transition-all"
            >
              Fix My Lead Flow — Free Audit
              <ArrowRight className="w-4 h-4" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ── What's Included ── */}
      <section className="py-24 px-6 bg-sky-50/40">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-sky-100 border border-sky-200">
              <span className="text-xs font-bold text-[#046BAF] tracking-widest uppercase">
                What&apos;s Included
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              Eight Deliverables That Build a Predictable, Qualified Lead Pipeline
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              Every Kazi Agency lead generation engagement includes these eight core deliverables — built, integrated, and continuously optimised as one connected system.
            </p>
          </motion.div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {deliverables.map((item, i) => {
              const Icon = item.icon;
              return (
                <motion.div
                  key={item.title}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.07 }}
                  className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-sky-200 hover:shadow-md transition-all"
                >
                  <div className={`${item.bg} w-11 h-11 rounded-xl flex items-center justify-center mb-4`}>
                    <Icon className={`w-5 h-5 ${item.color}`} />
                  </div>
                  <h3 className="font-bold text-slate-900 mb-2 text-sm leading-snug">{item.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed">{item.description}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── How a Lead Generation System Works ── */}
      <section className="py-20 px-6 bg-white border-y border-slate-100">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-sky-100 border border-sky-200">
              <span className="text-xs font-bold text-[#046BAF] tracking-widest uppercase">
                The Lead Journey
              </span>
            </div>
            <h2 className="text-2xl md:text-3xl font-semibold text-slate-900 mb-3 text-balance">
              From Anonymous Visitor to Qualified Opportunity — Automatically
            </h2>
            <p className="text-slate-500 max-w-2xl mx-auto text-base">
              Here&apos;s exactly what happens when a visitor lands on your website after a Kazi Agency lead generation system is in place.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-4 gap-6 relative">
            <div
              aria-hidden
              className="hidden md:block absolute top-[40px] left-[calc(12.5%+20px)] right-[calc(12.5%+20px)] h-px bg-gradient-to-r from-transparent via-sky-200 to-transparent"
            />
            {[
              {
                step: "01",
                icon: MousePointer,
                title: "Visitor Arrives",
                description: "A prospect lands via Google, a paid ad, social media, or referral. The chatbot engages within seconds. A lead magnet offer or smart form captures attention before they leave.",
                color: "text-[#046BAF]",
                bg: "bg-sky-50",
                border: "border-sky-100",
              },
              {
                step: "02",
                icon: Filter,
                title: "Qualified in Real Time",
                description: "The chatbot or smart form asks the right questions — budget, timeline, company size, specific need. Answers are scored instantly. Hot leads are routed to book. Cold leads enter nurture.",
                color: "text-cyan-600",
                bg: "bg-cyan-50",
                border: "border-cyan-100",
              },
              {
                step: "03",
                icon: Zap,
                title: "Instant Automated Follow-Up",
                description: "The moment a lead converts, personalised SMS and email sequences fire automatically. The right team member receives an instant notification with the lead's full context and score.",
                color: "text-teal-600",
                bg: "bg-teal-50",
                border: "border-teal-100",
              },
              {
                step: "04",
                icon: PhoneCall,
                title: "Sales-Ready in Your CRM",
                description: "A fully qualified, source-attributed lead appears in your GoHighLevel pipeline — with contact details, score, interaction history, and a warm sequence already in motion. Your team just has to close.",
                color: "text-indigo-600",
                bg: "bg-indigo-50",
                border: "border-indigo-100",
              },
            ].map((item, i) => {
              const Icon = item.icon;
              return (
                <motion.div
                  key={item.step}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  className={`relative bg-white rounded-2xl border ${item.border} p-6 hover:shadow-lg transition-all`}
                >
                  <div className="flex items-center gap-3 mb-4">
                    <div className={`${item.bg} ${item.border} border w-12 h-12 rounded-xl flex items-center justify-center shrink-0`}>
                      <Icon className={`w-5 h-5 ${item.color}`} />
                    </div>
                    <span className="text-3xl font-black text-slate-100 select-none leading-none">{item.step}</span>
                  </div>
                  <h3 className="font-bold text-slate-900 mb-2">{item.title}</h3>
                  <p className="text-sm text-slate-500 leading-relaxed">{item.description}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Tools Slider ── */}
      <section className="py-16 bg-white border-b border-slate-100">
        <div className="max-w-5xl mx-auto px-6 mb-10">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-sky-100 border border-sky-200">
              <span className="text-xs font-bold text-[#046BAF] tracking-widest uppercase">
                Our Lead Gen Stack
              </span>
            </div>
            <h2 className="text-2xl md:text-3xl font-semibold text-slate-900 mb-3">
              Integrated Tools That Work Together as One System
            </h2>
            <p className="text-slate-500 max-w-2xl mx-auto text-base">
              We connect best-in-class capture, qualification, CRM, and attribution tools into a single lead pipeline — so nothing is ever tracked in a spreadsheet again.
            </p>
          </motion.div>
        </div>

        <div className="relative overflow-hidden">
          <div className="absolute left-0 top-0 bottom-0 w-24 z-10 bg-gradient-to-r from-white to-transparent pointer-events-none" />
          <div className="absolute right-0 top-0 bottom-0 w-24 z-10 bg-gradient-to-l from-white to-transparent pointer-events-none" />

          <div className="flex gap-4 animate-scroll-left w-max px-6">
            {[...toolItems, ...toolItems].map((tool, i) => (
              <div
                key={`${tool.id}-${i}`}
                className="flex items-center gap-3 bg-white border border-slate-200 rounded-2xl px-5 py-3.5 shadow-sm hover:shadow-md hover:border-sky-200 transition-all shrink-0 cursor-default"
              >
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                  style={{ backgroundColor: tool.iconBg }}
                >
                  {tool.icon}
                </div>
                <div>
                  <p className="font-bold text-slate-900 text-sm leading-none mb-1">{tool.name}</p>
                  <p className="text-xs text-slate-400 leading-none">{tool.tagline}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <p className="text-center text-sm text-slate-400 mt-8 px-6">
          Works with any existing website — WordPress, Webflow, Wix, Squarespace, custom-built, or a landing page we build for you.
        </p>
      </section>

      {/* ── Our Process ── */}
      <section id="how-it-works" className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-sky-100 border border-sky-200">
              <span className="text-xs font-bold text-[#046BAF] tracking-widest uppercase">
                How It Works
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              From Leaky Funnel to Predictable Pipeline — Step by Step
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              A proven five-phase process — audit and strategy first, build second, automated system third, compounding results ongoing.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-5 gap-5 relative">
            <div
              aria-hidden
              className="hidden md:block absolute top-[52px] left-[calc(10%+24px)] right-[calc(10%+24px)] h-px bg-gradient-to-r from-transparent via-slate-200 to-transparent"
            />

            {buildSteps.map((step, i) => {
              const Icon = step.icon;
              return (
                <motion.div
                  key={step.step}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  className={`relative bg-white rounded-2xl border ${step.border} p-5 hover:shadow-lg transition-all`}
                >
                  <div className="flex items-center gap-3 mb-4">
                    <div className={`${step.bg} ${step.border} border w-12 h-12 rounded-xl flex items-center justify-center shrink-0`}>
                      <Icon className={`w-5 h-5 ${step.color}`} />
                    </div>
                    <span className="text-3xl font-black text-slate-100 select-none leading-none">
                      {step.step}
                    </span>
                  </div>
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">{step.duration}</p>
                  <h3 className="text-sm font-bold text-slate-900 mb-2">{step.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed">{step.description}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Comparison Table ── */}
      <section className="py-24 px-6 bg-sky-50/40">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-sky-100 border border-sky-200">
              <span className="text-xs font-bold text-[#046BAF] tracking-widest uppercase">
                Why Kazi Agency
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              Full Lead Generation System vs. Contact Forms, Standalone Tools & Typical Agencies
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              A contact form is not a lead generation strategy. Here&apos;s how an end-to-end system compares to every other option.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="overflow-x-auto rounded-2xl border border-slate-200 shadow-sm bg-white"
          >
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-200">
                  <th className="text-left p-5 font-semibold text-slate-700 min-w-[200px]">Feature</th>
                  {comparisonData.map((col) => (
                    <th
                      key={col.label}
                      className={`p-5 text-center font-bold text-sm min-w-[150px] ${
                        col.highlight ? "text-[#046BAF] bg-sky-50/60" : "text-slate-500"
                      }`}
                    >
                      {col.label}
                      {col.highlight && (
                        <span className="block mt-1 text-[10px] bg-[#046BAF] text-white px-2 py-0.5 rounded-full font-bold mx-auto w-fit">
                          Best Value
                        </span>
                      )}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {comparisonFeatures.map((feature, fi) => (
                  <tr
                    key={feature}
                    className={`border-b border-slate-100 last:border-0 ${fi % 2 === 0 ? "bg-white" : "bg-slate-50/40"}`}
                  >
                    <td className="p-5 font-medium text-slate-700 text-sm">{feature}</td>
                    {comparisonData.map((col) => {
                      const val = col.values[fi];
                      return (
                        <td
                          key={col.label}
                          className={`p-5 text-center ${col.highlight ? "bg-sky-50/30" : ""}`}
                        >
                          {val === true ? (
                            <Check className="w-5 h-5 text-[#046BAF] mx-auto" />
                          ) : val === false ? (
                            <X className="w-4 h-4 text-red-400 mx-auto" />
                          ) : (
                            <span className="text-xs text-slate-400 font-medium">{val as string}</span>
                          )}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-10 bg-white rounded-2xl border border-sky-200 p-8"
          >
            <div className="grid md:grid-cols-3 gap-6 text-center">
              {[
                {
                  title: "Basic Contact Form (DIY)",
                  cost: "Free — but costly",
                  note: "No qualification, no scoring, no automated follow-up, no attribution. You get a name and email — and no system to do anything useful with it. Most form submissions sit in an inbox until someone remembers to reply days later.",
                },
                {
                  title: "Standalone Tools (Typeform, Intercom)",
                  cost: "$50–$400/mo per tool",
                  note: "Individual tools solve individual problems. A quiz tool doesn't connect to your CRM. A chatbot doesn't fire follow-up sequences. Without integration, data is scattered, leads are lost, and nothing talks to anything else.",
                },
                {
                  title: "Kazi Agency — Complete Lead Gen System",
                  cost: "Monthly retainer — all included",
                  note: "Chatbot, smart forms, lead magnets, scoring, CRM integration, automated follow-up, and monthly reporting — all built, connected, and managed as one system. From anonymous visitor to qualified pipeline opportunity, automatically.",
                  highlight: true,
                },
              ].map((item) => (
                <div
                  key={item.title}
                  className={`rounded-xl p-5 ${item.highlight ? "bg-sky-50 border border-sky-200" : "bg-slate-50"}`}
                >
                  <p className={`font-bold mb-1 ${item.highlight ? "text-[#046BAF]" : "text-slate-700"}`}>
                    {item.title}
                  </p>
                  <p className={`text-xl font-black mb-2 ${item.highlight ? "text-[#046BAF]" : "text-slate-900"}`}>
                    {item.cost}
                  </p>
                  <p className="text-xs text-slate-500 leading-relaxed">{item.note}</p>
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Why Kazi Agency ── */}
      <section className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <motion.div
              initial={{ opacity: 0, x: -24 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-sky-100 border border-sky-200">
                <span className="text-xs font-bold text-[#046BAF] tracking-widest uppercase">
                  Why Choose Us
                </span>
              </div>
              <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-6 text-balance">
                We Build the System That Feeds Your Pipeline — You Focus on Closing
              </h2>
              <p className="text-lg text-slate-600 leading-relaxed mb-8">
                Most agencies generate leads and throw them over the fence. We build the entire capture-to-pipeline infrastructure: chatbots that qualify, forms that segment, scoring that prioritises, sequences that nurture, and CRM pipelines that give your sales team everything they need the moment a hot lead arrives. You don&apos;t manage the system — you benefit from it.
              </p>

              <div className="flex flex-col gap-4">
                {[
                  "AI chatbot qualified and captures leads 24/7 — not just during business hours",
                  "Every lead scored and routed before it reaches your inbox",
                  "Automated SMS and email follow-up fires in seconds, not hours",
                  "Full source attribution — know exactly which channel drives your best clients",
                  "All leads flow into GoHighLevel CRM with zero manual data entry",
                  "Monthly reporting tracks cost-per-lead and cost-per-client by channel",
                ].map((point) => (
                  <div key={point} className="flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-[#046BAF] flex-shrink-0 mt-0.5" />
                    <span className="text-slate-700 font-medium">{point}</span>
                  </div>
                ))}
              </div>

              <div className="mt-10">
                <Link
                  href="/book-a-consultation"
                  className="inline-flex items-center gap-2 bg-[#046BAF] hover:bg-[#035a94] text-white px-7 py-3.5 rounded-xl font-bold transition-all"
                >
                  Book a Free Lead Strategy Call
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 24 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="grid grid-cols-1 sm:grid-cols-2 gap-5"
            >
              {[
                {
                  icon: Bell,
                  title: "Instant Lead Alerts",
                  description:
                    "The moment a high-scoring lead converts, your team receives an instant SMS and email notification with the lead's name, contact details, qualification answers, and source. No checking dashboards. No delayed discovery.",
                },
                {
                  icon: Shield,
                  title: "No Leads Fall Through",
                  description:
                    "Every channel — website, landing pages, paid ads, social, and referral — feeds into one pipeline. Automated follow-up sequences handle leads your team can't reach immediately. Nothing sits in an inbox going cold.",
                },
                {
                  icon: DollarSign,
                  title: "Proven Cost-Per-Lead Reduction",
                  description:
                    "Better qualification at the top means your sales team spends time on leads worth their time. Clients typically see cost-per-qualified-lead drop by 30–50% within the first 90 days as the system filters out poor-fit enquiries.",
                },
                {
                  icon: TrendingUp,
                  title: "System Gets Smarter Over Time",
                  description:
                    "Lead scoring thresholds are refined monthly based on which leads actually closed. Chatbot flows are updated based on conversation drop-off data. The system improves continuously — lead quality compounds the longer it runs.",
                },
              ].map((point, i) => {
                const Icon = point.icon;
                return (
                  <motion.div
                    key={point.title}
                    initial={{ opacity: 0, y: 16 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                    className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-sky-200 hover:shadow-md transition-all"
                  >
                    <div className="bg-sky-50 w-11 h-11 rounded-xl flex items-center justify-center mb-4">
                      <Icon className="w-5 h-5 text-[#046BAF]" />
                    </div>
                    <h3 className="font-bold text-slate-900 mb-2">{point.title}</h3>
                    <p className="text-sm text-slate-500 leading-relaxed">
                      {point.description}
                    </p>
                  </motion.div>
                );
              })}
            </motion.div>
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="py-24 px-6 bg-sky-50/40">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-14"
          >
            <div className="inline-flex items-center gap-2 mb-4 px-4 py-1.5 rounded-full bg-sky-100 border border-sky-200">
              <span className="text-xs font-bold text-[#046BAF] tracking-widest uppercase">
                FAQ
              </span>
            </div>
            <h2 className="text-3xl md:text-4xl font-semibold text-slate-900 mb-4 text-balance">
              Common Questions About Lead Generation Services
            </h2>
            <p className="text-xl text-slate-600 max-w-2xl mx-auto">
              Straight answers to every question business owners ask before investing in a lead generation system.
            </p>
          </motion.div>

          <div className="flex flex-col gap-3">
            {faqs.map((faq, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
                className="bg-white rounded-2xl border border-slate-200 overflow-hidden"
              >
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between gap-4 p-6 text-left hover:bg-slate-50/50 transition-colors cursor-pointer"
                >
                  <span className="font-semibold text-slate-900 text-sm sm:text-base leading-snug">
                    {faq.q}
                  </span>
                  <ChevronDown
                    className={`w-5 h-5 text-[#046BAF] shrink-0 transition-transform duration-200 ${
                      openFaq === i ? "rotate-180" : ""
                    }`}
                  />
                </button>
                <AnimatePresence>
                  {openFaq === i && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.22 }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 pb-6 text-sm text-slate-600 leading-relaxed border-t border-slate-100 pt-4">
                        {faq.a}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="py-24 px-6 bg-gradient-to-br from-[#046BAF] to-cyan-600 relative overflow-hidden">
        <div aria-hidden className="absolute inset-0 pointer-events-none">
          <div className="absolute left-[-10%] top-[-20%] w-[500px] h-[500px] rounded-full bg-white/5 blur-3xl" />
          <div className="absolute right-[-8%] bottom-[-15%] w-[400px] h-[400px] rounded-full bg-cyan-300/10 blur-3xl" />
        </div>

        <div className="max-w-4xl mx-auto text-center relative">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <div className="inline-flex items-center gap-2 mb-5 px-4 py-2 rounded-full bg-white/15 border border-white/20">
              <Sparkles className="w-4 h-4 text-white" />
              <span className="text-xs font-bold text-white tracking-widest uppercase">
                Ready to Fill Your Pipeline?
              </span>
            </div>

            <h2 className="text-3xl md:text-4xl font-semibold text-white mb-6 text-balance">
              Let&apos;s Build a Lead Generation System That Qualifies and Delivers Prospects While You Sleep
            </h2>
            <p className="text-xl text-blue-100 mb-10 max-w-2xl mx-auto leading-relaxed">
              Book a free 30-minute lead audit. We&apos;ll review your current capture setup, identify where leads are leaking, and show you exactly what a complete, automated lead generation system looks like for your business.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/book-a-consultation"
                className="bg-white text-[#046BAF] hover:bg-blue-50 px-8 py-4 rounded-xl font-bold text-base transition-all inline-flex items-center gap-2 justify-center shadow-lg"
              >
                Book My Free Lead Audit
                <ArrowRight className="w-4 h-4" />
              </Link>
              <Link
                href="/services"
                className="bg-white/10 hover:bg-white/20 border border-white/30 text-white px-8 py-4 rounded-xl font-bold text-base transition-all inline-flex items-center gap-2 justify-center"
              >
                Explore All Services
              </Link>
            </div>

            <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-6 text-blue-100 text-sm">
              {["No commitment required", "Free 30-minute strategy call", "Full system audit included"].map((item) => (
                <div key={item} className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-cyan-200" />
                  {item}
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>
    </main>
  );
}
